### ISSUE TITLE
*** missing separator.  Stop.

### ISSUE THREAD

**Issue by magdesign** [pierrep/ofxVideoSync#1]
Just tried to compile on a Rpi3 with Debian Stretch 9.11.
But get following error:
`
/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk:210: *** missing separator.  Stop.`

**Comment by pierrep** [comment]
Can you post the contents of the addons.make in the directory you are compiling?

**Comment by magdesign** [comment]
```
ofxVideoSync
ofxOMXPlayer

```
Tried with adding a white space, did not help

**Comment by pierrep** [comment]
Can you add ofxOsc to that?

**Comment by pierrep** [comment]
by the way I've made a bunch of changes so things might be broken at the moment. I'm getting very close to finishing the ofxPiMapper integration

**Comment by magdesign** [comment]
adding ofxOsc did not help, no worries, I let you finish the changes and do the testing then....

**Comment by magdesign** [comment]
issue still persists:

```
Compiling example-videoSyncSender for Release
make[1]: Entering directory '/home/pvj/openFrameworks/addons/ofxVideoSync/example-videoSyncSender'
HOST_OS=Linux
checking pkg-config libraries:   cairo zlib gstreamer-app-1.0 gstreamer-1.0 gstreamer-video-1.0 gstreamer-base-1.0 libudev freetype2 fontconfig sndfile openal libcurl glfw3 rtaudio gtk+-3.0 libmpg123 
with PKG_CONFIG_LIBDIR=
/home/pvj/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/config.addons.mk:210: *** missing separator.  Stop.
make[1]: Leaving directory '/home/pvj/openFrameworks/addons/ofxVideoSync/example-videoSyncSender'
/home/pvj/openFrameworks/libs/openFrameworksCompiled/project/makefileCommon/compile.project.mk:124: recipe for target 'Release' failed
make: *** [Release] Error 2

```

**Comment by pierrep** [comment]
Can you try removing the addons_config.mk file and see if that helps?

**Comment by pierrep** [comment]
Actually the addons.make files in the examples should have both ofxOsc added as well.
I've been testing on Stretch and Buster. are you on Jessie?

**Comment by pierrep** [comment]
OK I've added ofxOsc to the two addons.make just now, just get latest.
